config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'posts#index', as: 'home'

  get 'about' => 'pages#about', as: 'about'
  resources :posts do
    resources :comments
  end

  resources :tags, only: [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :taggings, :dependent => :destroy
  has_many :tags, through: :taggings
  has_many :comments, :dependent => :destroy

  has_one :user

  def all_tags
    self.tags.map(&:name).join(', ')
  end

  def all_tags=(names)
    self.tags = names.split(',').map do |name|
      Tag.where(name: name.strip).first_or_create!
    end
  end
end

app/models/post_of_user.rb
class PostOfUser < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :taggings
  has_many :posts, through: :taggings

  def self.counts
    self.select("name, count(taggings.tag_id) as count").joins(:taggings).group("taggings.tag_id")
  end
end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :post
  belongs_to :tag
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  #def index
  # @comments = Comment.all
  # end

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(comment_params)
    redirect_to post_path(@post)
  end

  private

  def comment_params
    params.require(:comment).permit(:username, :body)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about

  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def show
    @post = Post.find(params[:id])
  end

  def create
    @book = Post.create()
    @post = Post.new(post_params)

    if @post.save
      redirect_to @post
    else
      render 'new'
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])

    if @post.update(post_params)
      redirect_to @post
    else
      render 'edit'
    end
  end

  def destroy
    @post = Post.find(params[:id])

    @post.destroy
    redirect_to posts_path
  end

  private

  def post_params
    params.require(:post).permit(:title, :brief, :body, :all_tags, :user_id)
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def show
    @tag = Tag.find_by(name: params[:id])
    @posts = @tag.posts
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css' %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  <nav class="navbar navbar-expand-lg navbar-light bg-dark">
    <%= link_to "NikoBlog", home_path, class: "navbar-brand text-warning font-weight-bold" %>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">

        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "Додати новий пост", new_post_path, class: "nav-link text-white"%>
          </li>
        <% end %>

      </ul>


      <% if user_signed_in? %>

        <div class="text-white">Привіт, <%= current_user.name%></div>

        <%= link_to "Вийти", destroy_user_session_path, method: :delete, class: "ml-3 btn btn-danger my-2 my-sm-0"%>

      <% else %>

          <%= link_to "Увійти", new_user_session_path, class: "ml-5 btn btn-success my-2 my-sm-0"%>

          <%= link_to "Зареєструватися", new_user_registration_path, class: "ml-3 btn btn-light my-2 my-sm-0"%>


      <% end %>
    </div>
  </nav>
  <!--<nav class="navbar navbar-expand navbar-dark bg-dark p-0">
    <div class="row">
      <div class="col">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item nav-link bg-success main font-weight-bold">
            <%= link_to "NikoBlog", home_path, class: "link" %>
          </li>

          <% if user_signed_in? %>
            <li class="nav-item nav-link ml-auto add item">
              <%= link_to "Додати новий пост", new_post_path, class: "link"%>
            </li>
          <% end %>
        </ul>
      </div>
      <div class="col">
        <ul class="ml-auto">


        </ul>
      </div>
      -->

    </div>



  </nav>

    <div class="container mt-4 mb-5">
      <%= yield %>
    </div>

  </body>
</html>

app/views/posts/edit.html.erb
<p class="post-title">Редагування</p>

<div class="container-info post-form p-2 mb-4">
  <%= form_for :post, url: post_path(@post), method: :patch do |f| %>

    <div class="mt-2">
      <label>Назва</label>
      <%= f.text_field :title, class: "form-control"%>
    </div>

    <div class="form-group mt-3">
      <p>Коротка інформація</p>
      <%= f.text_area :brief, class: "form-control"%>
    </div>

    <div class="mt-3 ">
      <p>Повна інформація</p>
      <%= f.trix_editor :body, class: "form-control body-info"%>
    </div>

    <div class="mt-5">
      <label>Теги</label>
      <%= f.text_field :all_tags, class: "form-control"%>
    </div>

    <%= f.submit class: "btn btn-block btn-success mt-5"%>

  <% end %>

</div>

app/views/posts/index.html.erb
  <p class="post-title">Усі пости</p>

  <div class="row">

    <div class="col-10">
      <% @posts.each do |post| %>
        <div class="post-index mt-5 p-2 border">
          <p class="text-muted float-right"><%= post.created_at.strftime("%B %d, %Y") %></p>
          <p class= "all-posts-title"><%= post.title %></p>
          <p сlass= "all-posts-brief"><%= post.brief %></p>
          <%= link_to "Читати далі...", post_path(post), class: "h6"%><br>
          <hr>
          <% if user_signed_in? && (current_user.id == post.user_id) %>
            <p class="text-left badge badge-warning border mb-2">Твій пост</p>
          <% end %>
          <%= raw post.tags.map(&:name).map{ |t| link_to t, tag_path(t),
                                                         class: 'badge badge-success'}.join(' ') %>
        </div>

      <% end %>
    </div>

    <div class="col mt-5">
      <div class="row">
        <% list = [] %>

        <% @posts.each do |post| %>

          <% post.tags.map(&:name).each do |tag| %>
            <% list.push(tag) %>
          <% end %>

        <% end %>

        <%= raw list.uniq.map{ |t| link_to "#"+t, tag_path(t),
                                           class: 'text-left col-11 badge badge-success border mb-2'}.join(' ') %>



      </div>
    </div>
  </div>

app/views/posts/new.html.erb
<p class="post-title">Додати новий пост</p>

<div class="container-info post-form p-2 mb-4">
    <%= form_for :post, url: posts_path do |f| %>

      <div class="mt-2">
        <label>Назва</label>
        <%= f.text_field :title, class: "form-control"%>
      </div>

      <div class="form-group mt-3">
        <p>Коротка інформація</p>
        <%= f.text_area :brief, class: "form-control"%>
      </div>

      <div class="mt-3 ">
        <p>Повна інформація</p>
        <%= f.trix_editor :body, class: "form-control body-info"%>
      </div>

      <div class="mt-5">
        <label>Теги</label>
        <%= f.text_field :all_tags, class: "form-control"%>
      </div>

      <%= f.hidden_field :user_id, :value => current_user.id %>

      <%= f.submit class: "btn btn-block btn-success mt-5"%>

    <% end %>

</div>

app/views/posts/show.html.erb
<div class="container-info mb-5 border mt-4 ">

  <div class="mb-3 p-1 post-title">
    <%= @post.title %>
  </div>

  <% if user_signed_in? && (current_user.id == @post.user_id) %>
    <p class="ml-2 text-left badge badge-warning border mb-2">Твій пост</p>
  <% end %>

  <%= raw @post.tags.map(&:name).map{ |t| link_to t, tag_path(t), class: 'ml-2 badge badge-success'}.join(' ') %>

  <p class="text-muted float-right mr-4"><%= @post.created_at.strftime("%B %d, %Y") %></p>

  <div class="mt-5 post-body">
    <p><%= @post.body.html_safe %></p>
  </div>



  <% if user_signed_in? && (current_user.id == @post.user_id) %>
    <hr>
  <div class="row ml-5">
    <%= link_to "Змінити", edit_post_path(@post),
                class: "mb-3 col-2 solid font-weight-bold text-center square_btn edit-button mr-3" %>

    <%= link_to "Видалити", post_path(@post), method: :delete, data: {confirm: "Хотите удалить статью?"},
                class: "mb-3 col-2 font-weight-bold text-center square_btn delete-button" %>
  </div>
    <% end %>
</div>


  <div class="mb-5 p-3 container-info border">
    <%= form_for([@post, @post.comments.build]) do |f| %>

      <% if user_signed_in? %>
        <%= f.hidden_field :username, :value => current_user.name %>
        <% else %>
        <div class="mt-2">
          <label>Користувач:</label>
          <%= f.text_field :username, class: "form-control"%>
        </div>
        <% end %>


      <div class="form-group mt-3">
        <p>Коментар:</p>
        <%= f.text_area :body, class: "form-control"%>
      </div>

      <%= f.submit "Додати коментар", class: "btn btn-block btn-success mt-5"%>

    <% end %>
  </div>


  <% if @post.comments.count != 0 %>
      <% @post.comments.each do |comment| %>
        <% if !comment.username.nil?  %>
          <div class="row mb-2">

            <div class="text-center">
              <p class="ml-3 text-muted p-2"><%= comment.created_at.strftime("%H:%M %d/%m/%Y") %></p>
            </div>

            <div class="text-center">
              <p class="ml-3 font-weight-bold text-success p-2"><%= comment.username %></p>
            </div>

              <p class="ml-3 comment border border-dark col p-2"><%= comment.body %></p>
          </div>
        <% end %>
    <% end %>
  <% end %>

app/views/tags/show.html.erb
<p class="post-title">#<%= @tag.name %></p>

<% if @tag.posts.empty? %>

  <p>На жаль, постів немає :(</p>

<% else %>

  <% @tag.posts.each do |post| %>


    <div class="post-index mt-5 p-2 border">
      <p class="text-muted float-right"><%= post.created_at.strftime("%B %d, %Y") %></p>
      <p class= "h3"><%= post.title %></p>
      <p><%= post.brief %></p>
      <%= link_to "Читати далі...", post_path(post), class: "h6"%><br>
      <hr>
      <%= raw post.tags.map(&:name).map{ |t| link_to t, tag_path(t), class: 'badge badge-success'}.join(' ') %>


    </div>

  <% end %>
<% end %>